version: "3.9"

services:
  api:
    build: ./app
    container_name: genesis-api
    restart: always
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:16
    container_name: genesis-db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=genesis
      - POSTGRES_PASSWORD=genesis
      - POSTGRES_DB=genesis
